### PR TITLE
add support for Hetzner Cloud floating-IPs

### PR DESCRIPTION
**Pull request by tpo**
Hi Cybertec,

this pull request adds support for Hetzner Cloud floating-IPs. Please pull.

Thanks & Greetings,
*t

### CODE REVIEW

**Comment by tpo** [comment]
please note that my branch https://github.com/tpo/vip-manager/tree/add_logging_to_hetzner_floating_IPs adds verbose loggin of the issued curl command and the JSON reply to this pull request, it however depends on the following pull request: https://github.com/cybertec-postgresql/vip-manager/pull/35 that adds the verbose loggin infrastructure to cybertec/vip-manager/master

**Comment by servergeeks** [comment]
Hi guys,

Is there something blocking this PR ? 
I'm currently using hcloud and would like to use this feature! 

Thanks!

br

**Comment by tpo** [comment]
> Hi guys,
> 
> Is there something blocking this PR ?
> I'm currently using hcloud and would like to use this feature!
> 
> Thanks!
> 
> br

The merge conflicts need to be resolved.

**Comment by tpo** [comment]
> > Hi guys,
> > Is there something blocking this PR ?
> > I'm currently using hcloud and would like to use this feature!
> > Thanks!
> > br
> 
> The merge conflicts need to be resolved.

I have rebased my patch onto the current master. I am testing whether all works as supposed right now.

**Comment by tpo** [comment]
So for some reason (advanced cross-branch merging seems to be way beyond me - I have *no idea* what git is actually doing) I was unable to rebase on the current upstream master.

Therefore I branched from upstream master and reapplied my changes. The new pull request is here: https://github.com/cybertec-postgresql/vip-manager/pull/58 .

@servergeeks : if you want to test, I can send you the resulting vip-manager by DM, let me know

**Comment by pashagolub** [comment]
Closed due to updated #58

**Pull request closed without merging**
