### PR TITLE
Improve ortography, fix option name in help text, rename method

### PR DESCRIPTION
**Pull request by tpo**
Please pull into uncurl branch

### CODE REVIEW

**Comment by tpo** [comment]
So for some reason, when I push further commits to my branch (point in case: the ["rename curlQueryFloatingIP -> queryFloatingIP" commit](https://github.com/cybertec-postgresql/vip-manager/pull/62/commits/c0b3721d9f692bc4a98cd24c48d536ceaf220049)) they get automatically included into the pull request for some reason.

I don't know how to work around that. So instead I'll rename the pull request to semanticall also include the mentioned commit. Oh well.

**Comment by tpo** [comment]
Now `queryFloatingIP` isn't a good name either. Because if we set the method parameter `post = true`, then we are not "querying" the api any more in the strict sense of the word.

I have not found a good name, but maybe:

* doWithqueryFloatingIpApi
* useFloatingIpApi
* talkToFloatingIpApi

?

**Comment by markwort** [comment]
how about callFloatingAPI ?

**Comment by tpo** [comment]
> how about callFloatingAPI ?

perfect

**Pull request merged**
