### PR TITLE
Fix README.md typo: VIP_INTERFACE -> VIP_IFACE

### PR DESCRIPTION
**Pull request by df7cb**

### CODE REVIEW

**Comment by markwort** [comment]
Hey @df7cb , thank you for your pull request. :+1: 

This environment variable is one of those that was changed with vip-manager 1.0 release, so now all references should be to the new flag (or key in the .yaml config file) `interface` or environment variable `VIP_INTERFACE`.

If you still use `VIP_IFACE` somewhere, you will be seeing an error like this:
```
[julian@fedora vip-manager]$ VIP_IFACE=eth0 vip-manager
2022/04/05 12:32:08 Parameter "VIP_IFACE" has been deprecated, please use "VIP_INTERFACE" instead
```

So I'm closing this as no longer applicable...

**Comment by markwort** [comment]
Thanks for pointing that out, here are some remarks:
- `README.md` : that is a section referencing how to upgrade from the old config to new config, so it only serves as an illustration for the older ExecStart lines that were common.
- `vipconfig/config.go` that is a comment explaining what has to be done to make sure that vip-manager can understand and complain that e.g. VIP_IFACE is a deprecated variable.
- `package/scripts/vip-manager` - this is only applicable to SysVinit systems...I'm planning to get rid of this completely, as far as we can see there is really no reason to support it any more.
- `package/config/vip-manager.default` - this either needs to be updated to bring it up to current expectations, or it needs to be dropped as well. I'd like the latter option, as I see little advantage in a file defining environment variables over a config file. But I also see that you are packaging this very file: https://salsa.debian.org/postgresql/vip-manager/-/blob/master/debian/rules#L20

What do you think, mainly on the last point?

**Comment by df7cb** [comment]
Ack, that sounds right.

**Comment by markwort** [comment]
And would you be fine with changing the packaging (at some point) to use the YAML config file, instead of the environment variables defined in `vip-manager.default` ?

**Comment by df7cb** [comment]
Cc: @mbanck

**Pull request closed without merging**
