### PR TITLE
Small improvements and adding the gratuitous arp

### PR DESCRIPTION
**Pull request by Faffnir**
Most of the explanation is done in the commit-comments.
Most importantly why we got rid of the arpqueryduplictes!

### CODE REVIEW

**Comment by martinseener** [comment]
I've seen this version with GARPs in action in our cluster and it works! This one fixes #1

**Comment by Faffnir** [comment]
I also changed the changelog-style to the gnu-changelog styleguide. I hope your ok with that @ants !

**Comment by ants** [comment]
Thank you so much for your work. Looks good to me. I'll take you on your word for now that it works, I'll try to get it setup on our test platform soon.

**Comment by martinseener** [comment]
@ants i've tested the new vip-manager yesterday together with @Faffnir in our environment with the GARP feature in different variations, for example, also what happens when the old master still has the VIP assigned on it's interface but the new master takes over and assigns itself the VIP and sends the GARP. Even then, the new master will be used by the other nodes. So for our tests, this version works great!

We will do more tests in the coming days and send fixes, if we find bugs anyways.

**Pull request merged**
